### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by kvnn** [Infotrend-Inc/OpenAI_WebUI#1]
Hi, I've been tempted to build a UI that wraps the Dall-e API, because I believe the quality is higher through the API than OpenAI's UI. Its hard to make a decision without seeing screenshots. You should add some to the Readme, if can.

Cheers,

- K

**Comment by mmartial** [comment]
I cannot comment on the difference between the API calls and regular use. 
You have access to more options from the API for `quality` and `style` as well as larger image sizes: `"1024x1024", "1024x1792", "1792x1024"`.
I have added a couple of screenshots of the WebUI in the README of v0.9.1 (in testing).
